#!/bin/bash

CONDA_OVERRIDE_CUDA="12.3" conda env update -p $NB_PYTHON_PREFIX --file environment-cuda.yml
conda activate sfn2025
conda clean --all -y
# because of symlinks and being in the container, this is where the Binder
# instance thinks the data should go.
NEMOS_DATA_DIR=/home/jovyan/data python ccn-software-sfn-2025/scripts/setup.py
mkdir -p notebooks
cp -r ccn-software-sfn-2025/notebooks/group_projects/ ./notebooks/
cp -r ccn-software-sfn-2025/notebooks/live_coding/ ./notebooks/
sed -i 's|../../docs/source/_static/|../../ccn-software-sfn-2025/docs/source/_static/|g' notebooks/*/*ipynb
